### ISSUE TITLE
Add Page Titles to Video Routes Using Helmet

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/youversion-web-open-ideas#12]
## Summary
Using `react-helmet`, add page titles and descriptions to each new route created in #10 and the mock API responses added in #11 .

## Variables in Titles and Descriptions
Some of the page titles and descriptions will require you to pull variables from the mock api responses. I've provided the related Bible.com URLs for comparison sake. But, instead of hard-coding exactly what you see on Bible.com, you'll need to use variables in your titles and descriptions. For example, `${video.title} - From ${publisher.name}`.

- [ ] Install `react-helmet` using `npm`, making sure it gets added as a dependency in `package.json`
- [ ] For path `/videos`, title and description should match: https://www.bible.com/videos
- [ ] For path `/videos/:id/series`, title and description should match: https://www.bible.com/videos/https://www.bible.com/videos/266/series
- [ ] For path `/videos/:slug`, title and description should match: https://www.bible.com/videos/269-why-have-you-forsaken-me-from-lightworkers-media

**Comment by michael-martin-al** [comment]
Yes. Precisely! Thanks Gale.

**Comment by WagicalGale** [comment]
Is this what you were thinking of? https://github.com/WagicalGale/youversion-web-open-ideas/commit/81a51809363673fcd459fa734b52e429649f2f49
