### ISSUE TITLE
Finish Building Out Full <Videos /> Component

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/youversion-web-open-ideas#14]
## Summary
Build a component for displaying a all the title video cards (the <TitleVideo/> component is being built in #13 ). Your job is to create a very similar user interface as https://www.bible.com/videos using only components from our `melos` component library: https://github.com/lifechurch/melos . If you start working on this issue before #13 is complete, feel free to put an empty placeholder component in place.

You won't be able to recreate the exact look and feel that you see on [the Bible.com videos page](https://www.bible.com/videos), but that's OK! 😄 What you see on Bible.com represents our old design style, but `melos` represents our newest design specs. I am sure you'll have questions, so feel free to ping me. We'll get one of our YouVersion designers to give you the final 👍  when you're done. So, you can expect there to be some back and forth work with them getting it just right.

## Mock API Data
After #11  has been completed, there should be some mock data available to use while building your component. Instead of hard-coding the strings and images, you want to grab those from the mock api data. If you have questions about this, just make a comment here and we'll do our best to answer quickly.

## This is What You're Building
![image](https://user-images.githubusercontent.com/3265272/38435723-332ae718-3998-11e8-9f1f-411a7a231c4a.png)

Essentially, you're going to use `<Heading1 />` from `melos` at the top of the page. Then, place an array of `<TitleVideo />` components in a two-column grid.

**Comment by adamaverycole** [comment]
I'll take this.

**Comment by adamaverycole** [comment]
Is this component supposed to be a reusable component like the components in Melos or is it supposed to be a "page" component?

I think your answer will determine how I provide the data to it.

**Comment by michael-martin-al** [comment]
@adamaverycole it will be a page component.

**Comment by adamaverycole** [comment]
@michael-martin-al Thank you, sir.
