### ISSUE TITLE
Finish building out <Video /> Component

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/youversion-web-open-ideas#19]
## Summary
Finish building out the `<Video />` component for displaying all the details of a single video (the <VideoPlayer /> component is being built in #18 ). Your job is to create a very similar user interface as https://www.bible.com/videos/269-why-have-you-forsaken-me-from-lightworkers-media using only components from our `melos` component library: https://github.com/lifechurch/melos . If you start working on this issue before #18 is complete, feel free to put an empty placeholder component in place.

You won't be able to recreate the exact look and feel that you see on [the Bible.com videos page](https://www.bible.com/videos/269-why-have-you-forsaken-me-from-lightworkers-media), but that's OK! 😄 What you see on Bible.com represents our old design style, but `melos` represents our newest design specs. I am sure you'll have questions, so feel free to ping me. We'll get one of our YouVersion designers to give you the final 👍  when you're done. So, you can expect there to be some back and forth work with them getting it just right.

## Mock API Data
After #11  has been completed, there should be some mock data available to use while building your component. Instead of hard-coding the strings and images, you want to grab those from the mock api data. If you have questions about this, just make a comment here and we'll do our best to answer quickly.

## This is What You're Building
![image](https://user-images.githubusercontent.com/3265272/38438640-b224c478-39a0-11e8-95e9-676fafa72942.png)

**Comment by WagicalGale** [comment]
I'm working on this at the moment! Could you give me some guidance on how to improve on what I have in my branch so far: https://github.com/wagicalgale/youversion-web-open-ideas/tree/add-videos-page

Thanks :)

**Comment by michael-martin-al** [comment]
It's difficult to say for sure without seeing the code in action, but it looks like you're headed in the right direction. Once you submit a PR, it will automatically deploy your version of the app so I can see it. Feel free to submit a PR just for the sake of starting this review, even if you're not 💯complete yet.

**Comment by glasssd** [comment]
@WagicalGale , in case you're interested, I have the instructions for deploying a fork to Netlify for demo purposes. I just submitted the PR, but in the interim you can access them here <https://github.com/glasssd/youversion-web-open-ideas/blob/master/README-DEPLOY.md> if that would help.

**Comment by WagicalGale** [comment]
@glasssd that's great, thanks for putting the work into that 👍
