### ISSUE TITLE
Configure ESLint for this Repo

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/youversion-web-open-ideas#4]
#2 needs to be merged before this makes sense

## Summary
We need someone to configure `eslint` on this repo and set the rules to match the existing set of rules we use for Bible.com. This will ensure that all contributors are working with the same standard in mind.

## TODO
- [x]  Follow instructions from ESLint to [Get Started with Local Usage](https://eslint.org/docs/user-guide/getting-started#local-installation-and-usage) * We extend the AirBNB config
- [x]  Modify `.eslintrc.js` to match the one we use for Bible.com (see below)

## Existing ESLint Configuration for Bible.com
```
module.exports = {
	"installedESLint": true,
	"ecmaFeatures": {
		"arrowFunctions": true,
		"binaryLiterals": true,
		"blockBindings": true,
		"classes": true,
		"defaultParams": true,
		"destructuring": true,
		"forOf": true,
		"generators": true,
		"modules": true,
		"objectLiteralComputedProperties": true,
		"objectLiteralDuplicateProperties": true,
		"objectLiteralShorthandMethods": true,
		"objectLiteralShorthandProperties": true,
		"octalLiterals": true,
		"regexUFlag": true,
		"regexYFlag": true,
		"restParams": true,
		"spread": true,
		"superInFunctions": true,
		"templateStrings": true,
		"unicodeCodePointEscapes": true,
		"globalReturn": true,
		"jsx": true,
		"experimentalObjectRestSpread": true,
		"experimentalClassProperties": true
	},
	"env": {
	  "browser": true,
	  "node": true,
	  "jasmine": true,
		"cypress/globals": true
	},
	"plugins": [
		"react",
		"cypress"
	],
	"parser": "babel-eslint",
	"extends": "airbnb",
	"rules": {
		"semi": 0,
		"max-len": 0,
		"object-curly-spacing": [2, "always"],
		"indent": [2, "tab", { "SwitchCase": 1 }],
		"no-unused-vars": 1,
		"no-underscore-dangle": 0,
		"one-var": 0,
		"one-var-declaration-per-line": 0,
		"no-multiple-empty-lines": 0,
		"no-negated-condition": 0,
		"arrow-parens": 0,
		"arrow-body-style": [ 1, "always" ],
		"comma-dangle": 0,
		"camelcase": 0,
		"padded-blocks": 0,
		"eol-last": 0,
		"array-bracket-spacing": 0,
		"no-useless-escape": 0,
		"no-tabs": 0,
		"operator-linebreak": 0,
		"no-control-regex": 0,
		"no-else-return": 0,
		"no-plusplus": 0,
		// jsx rules
		"jsx-quotes" : 0,
		"react/jsx-filename-extension": [0, { "extensions": [".js", ".jsx"] }],
		"react/display-name": 0,
		"react/no-danger": 0,
		"react/forbid-prop-types": 0,
		"react/jsx-boolean-value": 0,
		"react/jsx-closing-bracket-location": 1,
		"react/jsx-curly-spacing": 0,
		"react/jsx-handler-names": 1,
		"react/jsx-indent-props": [1, "tab"],
		"react/jsx-indent": [1, "tab"],
		"react/jsx-key": 1,
		"react/jsx-max-props-per-line": 0,
		"react/jsx-no-bind": 0,
		"react/jsx-no-duplicate-props": 1,
		"react/jsx-no-literals": 0,
		"react/jsx-no-undef": 1,
		"react/jsx-pascal-case": 1,
		"react/jsx-sort-prop-types": 0,
		"react/jsx-sort-props": 0,
		"react/jsx-uses-react": 1,
		"react/jsx-uses-vars": 1,
		"react/no-danger": 1,
		"react/no-deprecated": 1,
		"react/no-did-mount-set-state": 1,
		"react/no-did-update-set-state": 0,
		"react/no-direct-mutation-state": 1,
		"react/no-is-mounted": 1,
		"react/no-multi-comp": 0,
		"react/no-set-state": 0,
		"react/no-string-refs": 0,
		"react/no-unknown-property": 1,
		"react/prefer-es6-class": 1,
		"react/prop-types": 1,
		"react/react-in-jsx-scope": 1,
		"react/require-extension": 1,
		"react/self-closing-comp": 1,
		"react/sort-comp": 1,
		"react/wrap-multilines": 1
	}
}
```

**Comment by rnice01** [comment]
Hey, what version of Eslint and the other plugins are you guys running for use with that .eslintrc file? I started a branch with the latest version Eslint (4.19.0) but I'm getting a linting error saying the configuration file is invalid because of the "top-level property "installedESLint".

Checked the Eslint docs and don't see anything about how to configure a rule for "installedESLint", so maybe the latest version dropped support for it?

**Comment by michael-martin-al** [comment]
Hmm.. not sure why that's there. Let's just remove that first line and use the latest eslint version. Thanks for digging into that @rnice01

**Comment by rnice01** [comment]
@michael-martin-al Thanks for the reply, I'll update the branch to reflect that change. Just a couple of other notes:

- 'ecmaFeatures'  is no longer a top level rule and is now nested under parserOptions as documented [here ](https://eslint.org/docs/4.0.0/user-guide/configuring)

- jsx rule 'react/wrap-multilines' appears to be deprecated and replaced with 'react/jsx-wrap-multilines' noted in in the eslint-plugin-react changelog [here](https://github.com/yannickcr/eslint-plugin-react/blob/abe8381c0d6748047224c430ce47f02e40160ed0/CHANGELOG.md)

- 'react/require-extensions' has been removed and now the eslint-plugin-import extension rules are to be used [changelog](https://github.com/yannickcr/eslint-plugin-react/blob/abe8381c0d6748047224c430ce47f02e40160ed0/CHANGELOG.md). Any suggestions as to what to set the rules to? I set it to 'ignorePackages' and require an extension for every other type of file.

**Comment by michael-martin-al** [comment]
Wow. How did this config ever work for us? 😞 Obviously, we haven't updated our `eslint` package in a while. It sounds like you can easily move things around for the first two bullets. For the third bullet, let's just go with the default setting and we can change it later if it presents a problem. Let's set `react/no-danger` to generate an error, and we can manually exclude any files that need to violate this rule. We have a few cases where our API returns HTML and we must use `dangerouslySetInnerHtml` but we use it infrequently.

**Comment by rnice01** [comment]
@michael-martin-al thanks for the quick replies! I saw @adamaverycole 's PR got merged in so I'll update my branch and make all the necessary changes.
