### ISSUE TITLE
Add CodeClimate badges to README

### ISSUE THREAD

**Issue by tcg** [lifechurch/youversion-web-open-ideas#7]
@michael-martin-al  added CodeClimate webhooks for this project (🎉🎈), but it's currently not obvious until a Pull Request is opened (😕). 

It would add visibility and insight if we used the "badges" from CodeClimate in the top of our README file! 

This might make a great first task for someone who is interested in making their first Pull Request, or editing some Markdown. 

So if this task seems "very simple" to you, perhaps bring someone else along, and teach them something new! =) 

---

Here's an example of a CodeClimate "badge" might looks like, in another project of ours, if you haven't seen them here on Github: 

![image](https://user-images.githubusercontent.com/575773/38385025-5e7b7efe-38d6-11e8-9390-7e606df72cea.png)

--- 

- CodeClimate badges snippets are available at https://codeclimate.com/github/lifechurch/youversion-web-open-ideas/badges
- The README is a Markdown file, so you'd want to edit the Markdown version of the snippets.

**Comment by glasssd** [comment]
I appreciate the baby steps. :)

**Comment by glasssd** [comment]
@tcg 
I'm a newb with Git. I noticed that I had two commits in my PR (one where I updated my fork and another with my actual change). Should I delete and recreate my forks to avoid that commit count bump?

**Comment by adamaverycole** [comment]
@glasssd, you can squash commits together if you would like to do that.

**Comment by tcg** [comment]
@glasssd Welcome to the fun! It's very flexible, so can be confusing for quite a while. If you haven't already read it, *my* favorite Git resource is https://git-scm.com/book/en/v2 ... It suited the way I tend to learn. Sections 2 and 3 cover probably 95% of usual git tasks. 

Meanwhile...  Not concerned about commit counts, and I think the extra merge commit isn't going to hurt anything in this case, so I'll get this pulled in! 

Thanks so much for handling that!
